version: '3'
services:
  web-server:
    build:
      dockerfile: ./php.Dockerfile
      context: .
    restart: always
    volumes:
      - '.:/var/www/html/'
    ports:
      - "8080:80"
  mysql-server:
    image: mysql
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: appDB
    volumes:
      - ./page/database:/docker-entrypoint-initdb.d/
volumes:
  mysql-data: