version: '3.9'
services:
  ap_php_pgsql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './app:/var/www/html'
    ports:
      - '8080:80'
      - '5432:5432'

  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: evendot@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'

