version: '3.9'
services:
  apache:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/var/www/html/'
    ports:
      - '8080:80'
#  mysql-server:
#    image: mysql
#    container_name: mysql_server
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: appDB
#    volumes:
#      - ./page/database:/docker-entrypoint-initdb.d/