version: '3.9'
services:
  ap_php_pgsql:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - './database:/docker-entrypoint-initdb.d/'
    ports:
      - '8080:80'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: evendot@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'

